#!/usr/bin/env zsh
#
SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"
HW_MODEL=$(sysctl hw.model)
if [[ "$HW_MODEL" =~ "Air" ]]; then
  source "$SKETCHYBAR_CONFIG/sketchybarrc-no-notch"
else
  source "$SKETCHYBAR_CONFIG/sketchybarrc-notch"
fi
